version: "3.8"

services:

  postgres:
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: aom
      POSTGRES_DB: nestjs 

    ports:
      - 5432:5432